# Generated by Django 4.0.4 on 2024-10-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(blank=True, related_name='journeys', to='station.crew'),
        ),
    ]
