# Generated by Django 4.0.4 on 2024-10-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_journey_crew'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('journey', 'cargo', 'seat')},
        ),
    ]
